### PR TITLE
Add more general accessibility tests

### PR DESCRIPTION
**Pull request by PaulMorris**
These tests cover the pages that can be accessed (1) without logging in, or (2) by logging in as a provider that aren't (a) part of the enrollment steps, (b) the help documentation, or (c) the quick search results page.

There are a lot of commits here but most are quite similar.  (I could not find a way to reduce the repetition and still do things in the Serenity BDD way.  I'd be glad to know if I'm missing something.)

Tested by running the accessibility tests, and they all pass.

Issue #518 Implement accessibility checking in CI

### CODE REVIEW

**Comment by jasonaowen** [comment]
@PaulMorris PR #671 replaces this one, right?

**Comment by PaulMorris** [comment]
@jasonaowen Yeah, that's right.

**Comment by cecilia-donnelly** [comment]
Should we close this one then, @PaulMorris?

**Comment by PaulMorris** [comment]
@cecilia-donnelly Yeah, closing now that the other one has landed.

**Pull request closed without merging**
