### PR TITLE
Fix button accessibility where there are more than one submit button per form

### PR DESCRIPTION
**Pull request by PaulMorris**
Fixes the accessibility of submit buttons for forms with multiple submit buttons (and/or use the JS function `submitFormById` with two arguments).  These forms/buttons are found on these pages:
 -  the provider enrollment steps pages, e.g. the `Previous`, `Next`, `Save as Draft` buttons
 -  the `Edit Enrollment` page.  Log in as a service admin, click enrollments tab, click pending tab, click `edit` link for one of the items in the list.  The buttons are the navigation tabs `Personal Info`, `License Info` etc. and two at the bottom `Re-Submit Enrollment` and `Save Note`.   (This is the `edit_details.jsp` template.)

We stop using the JS function `submitFormById` and instead use parameters in the request that is sent when the buttons are clicked.  Then we use a new Java method to determine the destination page/url from the data in the parameters.

Tested by manually filling out a provider enrollment and editing an enrollment as a service admin, and confirming the buttons work as expected.  (Note that currently to test `Re-Submit Enrollment` you need to apply the changes described in the diff in the description of PR #560, as described there.)  The web UI tests also run successfully.

One similar form (in `provider/profile/list.jsp`) will be fixed separately, as suggested by @jasonaowen in Issue #553.  

Thanks @jasonaowen for helping with the fix for these.

Issue #553 Use accessible submit buttons on all forms

### CODE REVIEW

**Comment by PaulMorris** [comment]
With this PR the tabs on the `Edit Enrollment` pages (the `edit_details.jsp` template) look like buttons instead of tabs.  A follow-up will be needed to fix the CSS to make them look like tabs again.

**Comment by jasonaowen** [comment]
@PaulMorris would you mind splitting the `Edit Enrollment` changes into their own PR? That way we can get the improvement to the enrollment steps in, and get the CSS fixes with the rest of the `Edit Enrollment` changes.

**Comment by PaulMorris** [comment]
Good call @jasonaowen .  I think I will just split off the `Edit Enrollment` changes that affect the tabs, the ones that need the CSS changes.  That way we'll still fix the submit button accessibility issue for that page (via the other buttons on the page).

**Comment by PaulMorris** [comment]
Latest revision omits the changes related to tabs in `Edit Enrollment` and moves the new Java method to a better place in the file.

**Pull request merged**
