### PR TITLE
Update demo script and add new database dump files

### PR DESCRIPTION
**Pull request by PaulMorris**
Revise the demo scripts file for MESC 2018, and add two new database dump files for setting up the database for the demo.  Thanks to @frankduncan for the database dumps!

### CODE REVIEW

**Comment by frankduncan** [comment]
I also added two additional databases, for drafts without report data, and for just the excluded1/provider1 users with nothing else in the database.

**Comment by frankduncan** [comment]
Jenkins, test this please.

**Comment by jasonaowen** [comment]
I reduced the number of integration test results to keep, and manually deleted several of the oldest ones to unblock the builds.

Jenkins, test this please.

**Comment by jasonaowen** [comment]
The automatic cleanup happens after the integration tests run, and apparently I didn't manually delete enough builds (and so free up enough space) to unblock some of the other jobs. Now that the integration tests have run and automatically cleaned up old results, there is plenty of free space.

Jenkins, test this please.

**Comment by jasonaowen** [comment]
I fixed this for another PR, but to document what went happened:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

This is caused by me neglecting to add the `--no-daemon` gradle argument in the job configuration. I have since added it.

Jenkins, retest this please.

**Pull request merged**
