### PR TITLE
Fix accessibility of submit buttons that call JS functions

### PR DESCRIPTION
**Pull request by PaulMorris**
Fixes accessibility of submit buttons for forms where the buttons were directly making JS function calls such as `submitFormById` from their `href` or `onclick` attributes.  (As opposed to calling JS functions that were attached as a click handler to the `click` event.)

Tested by logging in as admin, navigating to the Category of Service page and confirming that the `Save` button on that page works.  The Web UI tests also pass.

Issue #553 Use accessible submit buttons on all forms

### CODE REVIEW

**Comment by jasonaowen** [comment]
What is your plan for styling the new buttons, @PaulMorris? In most cases there's only `<button>`s in a form, but in some cases, like Categories of Service, there's a `<button>` right next to a `<a>` link, which looks a little jarring:
cos

**Comment by jasonaowen** [comment]
Also, the COS form still includes the old style buttons when some categories of service are defined:
cos-buttons
I think you probably already know that :smiley: just making sure they're on your list!

**Comment by jasonaowen** [comment]
I was able to successfully test several buttons, and they worked as expected:
- Register, on the self registration page
- Save, on the admin page for editing categories of service on an approved enrollment
- Save, on the admin page for editing categories of service on a pending enrollment
- Approve, on the admin page for reviewing pending enrollments (also, wtf, why can you reject an enrollment with a `GET` request?)
- Reset Password, on the forgot password page
- Filter, on the provider dashboard page
- Filter, on the provider enrollments list

**Comment by jasonaowen** [comment]
However, I wasn't able to use the Practice Lookup feature; it is now giving me an error:

> Request method 'GET' not supported

I haven't yet compared that to the behavior on master, and unfortunately I won't be able to today.

**Comment by PaulMorris** [comment]
Thanks for the review @jasonaowen !  

On the CSS differences betweeen the old and new buttons, I have that in my to do list for after the current accessibility work (that's higher priority).  My plan is for the old buttons to be styled so they go with the new ones, and to improve the new style so it looks better (and so it looks more like the old button style).  That should be doable even if we leave some as `<a>` elements.  Although, it might make sense to convert them all to `<button>`s.  The `<span>`s that are currently there just for styling should be removed in any case.

I can check the Practice Lookup feature on master and see if that is a regression introduced by this PR.

**Comment by PaulMorris** [comment]
@jasonaowen I did not see that Practice Lookup error on the master branch.  Sorry I did not catch it before.  I'll look into fixing it in a revision of this PR.

**Comment by PaulMorris** [comment]
This latest revision fixes the problem with the `Practice Lookup` feature.  The event handler for the search button was not being attached, so `event.preventDefault()` wasn't being called and thus the `GET` error.  

The fix was to move the code that attaches that event handler function into the `$(document).ready` function so it would be attached after the document was ready (and not attempt to do so before, and fail).  I made the same change for the COS save buttons (although they happened to be working before).  

I also fixed the CSS for the Practice Lookup search button so it would be centered like before, rather than aligned all the way over to the left of the modal.

I tested these buttons and they worked as expected:
 - Search, in the practice lookup modal in the practice info enrollment step
 - Save, on the admin page for editing categories of service on an approved enrollment
 - Save, on the admin page for editing categories of service on a pending enrollment

**Comment by jasonaowen** [comment]
:+1: Thanks @PaulMorris, that fix makes sense to me! The good looks good, but I haven't tested it yet - @cecilia-donnelly, would you mind taking a pass? If it works for you, I'm :+1: to merge.

**Comment by PaulMorris** [comment]
@cecilia-donnelly Good question.  I assume they used `submitFormById` because they were using their own custom buttons made from `<a>` and `<span>` tags (presumably for aesthetic reasons?) where "submit" wouldn't work as on `<button>`.  Possibly also so they didn't have to put the buttons inside the form and could submit it from anywhere on the page?

`submitFormById` has some extra code to prevent double submissions (presumably needed for non-standard form submission buttons), but other than that I'm pretty sure it just submits the form:

```
/**
 * Submits the form with the given id.
 * @param id the id of the form to be submitted
 */
function submitFormById(id, url) {
  if (url) {
    $('#' + id).attr("action", url);
  }

  if (!screenLock) {
    screenLock = true;
    $('#' + id).submit();
  }
}
```

**Pull request merged**
