### PR TITLE
Expired session error from admin profile page #431

### PR DESCRIPTION
**Pull request by dan9000**
Add path prefixes of the profile pages to spring-security.xml

### CODE REVIEW

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Comment by jasonaowen** [comment]
@dan9000, would you mind [rewording the commit message](https://github.com/SolutionGuidance/psm/blob/master/CONTRIBUTING.md#commit-messages), please? Something like:

> Add Spring Security rules for profile pages
>
> (description of the problem and why this fixes it)
>
> Issue #431 Expired session doesn't redirect to login from "profile" page

**Comment by dan9000** [comment]
@jasonaowen I modified the amended message

**Comment by jasonaowen** [comment]
@dan9000 thank you! Please rebase so that there is only one commit, and then I think this'll be ready to merge.

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Comment by jasonaowen** [comment]
Hm, I'm able to reproduce the integration test errors locally, but one of them is also showing up on `master`. @dan9000, can you please start looking into the test failures?

**Comment by jasonaowen** [comment]
Jenkins, retest this please. (Why are the integration tests failing? Do they do so consistently? ([Failed build](https://ci.psm.solutionguidance.com/job/integration-tests/56/))).

**Comment by jasonaowen** [comment]
After talking with @PaulMorris, it seems the test failure I'm encountering locally is unrelated to this, and is instead caused by #672. Paul was able to run the integration tests on this PR successfully (and, presumably, so was @dan9000), so now I'm trying to figure out why Jenkins is having a hard time with them.

**Comment by dan9000** [comment]
@jasonaowen I modified this and fixed two of the tests. I think the one failing is the same you were referring to:
`Accessibility Checks. Dashboard Page` `I should have no accessibility issues(src/test/resources/features/general/accessibility.feature:12)`

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Pull request merged**
