### PR TITLE
376 fix right justified colons on forms

### PR DESCRIPTION
**Pull request by lorinpa**
Remove colons between labels and fields, on the following page:

On the provider 'View Enrollment Details' page:

- 'Personal Info' tab
- 'Practice Info' tab
- 'License Info' tab

	
Issue #376 Remove colons between form labels and fields

### CODE REVIEW

**Comment by lorinpa** [comment]
@jasonaowen Hi Jason, can you please review this pull request. Still not able to request reviewers yet.

Thank you

**Comment by lorinpa** [comment]
@jasonaowen HI Jason,
Will be  happy to make the requested changes. Will get back to this, June 28.

**Comment by lorinpa** [comment]
@jasonaowen Hi Jason,
I have a question regarding your comment:
> "we should be clear that these are changing the **summary pages** rather than the input forms."


The full path of the source file 'tribal_information.jsp' includes a sub-directory called '**summary**'. 
E.G. (psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/**summary**/tribal_information.jsp).

The source file 'tribal_information.jsp' is also displayed in the following application contexts:

 * 'Dashboard' Tab > 'View Enrollment Details' > 'License Info'
 * 'Enrollments' Tab > 'Create New Enrollment' > 'License Info' (I.E. an html input form).

Thus, does your use of the term "summary" refer to where 'tribal_information.jsp' resides in the source tree (I.E. 'summary' sub-directory)? 

Or, does your use of the term "summary" refer to the application context 'Dashboard' Tab > 'View Enrollment Details' ?

Hope that makes sense.  I am trying to use the appropriate language in the commit message edits.
Lorin

**Comment by jasonaowen** [comment]
Hi @lorinpa ! It looks to me like all the JSP files changed in this pull request are used to display information, rather than collect input, as I inferred from reading "on <something> info step" in the commit messages. Perhaps "summary" is the wrong word, since we do have that subdirectory; maybe "display" would be more appropriate?

**Comment by lorinpa** [comment]
@jasonaowen Hi Jason,
Thank you for the clarification. 

I believe (most if not all the files changed) are used both to collect input, as well as "display" (E.G. 'Dashboard' Tab > 'View Enrollment Details' ). 

Thus, I will provide those "dual purpose" details in the commit message edits. (ETA tomorrow :) )

**Comment by jasonaowen** [comment]
@lorinpa, it looks like something strange happened! This PR now wants to merge 35 commits, rather than three.

Please rebase onto master and force-push over your branch, and make sure that there are only the commits you intended.

**Comment by lorinpa** [comment]
@jasonaowen Hi Jason,
Thank you. Will do.

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Pull request merged**
