### PR TITLE
STAGING PR: Migration progress

### PR DESCRIPTION
**Pull request by slifty**
The first of many migration Pull Requests

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Jenkins, retest this please.

**Comment by cecilia-donnelly** [comment]
Jenkins, retest this please.

**Comment by slifty** [comment]
Jenkins, retest this please

**Comment by jasonaowen** [comment]
From the [console log](https://ci.psm.solutionguidance.com/job/integration-tests/Browser=chromium/298/console):

> Unexpected error running Liquibase: Error parsing line 233 column 36 of db/changelog/db-changelog-1.0.xml: cvc-complex-type.3.2.2: Attribute 'defaultValue' is not allowed to appear in element 'constraints'.

**Comment by jasonaowen** [comment]
Also, now that #810 is merged, this will need to be rebased to remove the cherry-picked commit.

**Comment by frankduncan** [comment]
Comment I made at https://github.com/SolutionGuidance/psm/pull/817#issuecomment-389116640 probably belongs here.

**Comment by slifty** [comment]
This PR is being broken into smaller pieces and served its purpose!  Closing.

**Pull request closed without merging**
