### PR TITLE
Require contact email for organizational applications: #770

### PR DESCRIPTION
**Pull request by cecilia-donnelly**
Since we are using the contact email address to send notifications, it
should be required.  Without it, submitting the enrollment gives the
user an unexplained "server error."

Update integration tests to include the contact email for organizational
applications now that this field is required.

Pulling this out from PR #771 to catch this problem before it causes more errors.  As it is now it's pretty easy to run into an exception on master that only shows up when an enrollment is actually submitted.  To test, create an organizational enrollment and leave the contact email blank.  You should get an error that prevents you from moving to the next page of the form.

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Jenkins, test this please.

(Spamming because of [this error](https://issues.jenkins-ci.org/browse/JENKINS-46183).)

**Comment by cecilia-donnelly** [comment]
@frankduncan I see the difference.

When the contact email is left blank, the error and alert show up correctly:

screenshot-2018-5-25 personal information 1

But when "same as above" is checked and personal email is left empty, the PSM doesn't indicate that the *personal* email would need to be filled in as contact email:
screenshot-2018-5-25 personal information 2

I'm not sure how to fix that, but I will look into it.

**Comment by cecilia-donnelly** [comment]
Most of the integration test failures on Jenkins do not happen for me locally.  Two do:

- Provider Types Report.Can Access Provider Types Page FAILED
- Provider Types Report.Can Filter Provider Types Page FAILED

I'll look into these two.  The other failures are largely accessibility test failures for the admin view of various enrollment pages, which I wouldn't expect these changes to affect, and yet apparently they do.  I don't see those failures locally, though -- perhaps they're a result of incomplete sample data?

**Comment by jasonaowen** [comment]
@cecilia-donnelly and I just spoke on the phone about this, and I want to capture and expand on what we talked about.

Setting the contact as non-null in the database is a good thought, but the way that the entities are constructed from their JAXB representation counterparts is convoluted enough that it's difficult to ensure they're created in the right order everywhere. In fact, it's difficult to even be certain that this rule does necessarily always mean that there should be a `ContactInformation` for every `Entity`, as there are more `Entity`s than just the provider - think independent members of an organization, beneficial owners, and so on. I think for the purpose of this PR, it's okay to leave the non-null constraint off, and record in #57 that maybe it should be non-null.

Secondly, we talked through fixing the error presentation. I suspect that we need to update the [code for translating errors reported by Drools into form errors](https://github.com/SolutionGuidance/psm/blob/bcab22c4ec8ccc5f7b2c7b2a9519a5c1b09d032f/psm-app/services/src/main/java/gov/medicaid/binders/PersonalInformationFormBinder.java#L192-L194) to check if the "same as above" checkbox is checked, and highlight different input elements accordingly.

**Comment by cecilia-donnelly** [comment]
Okay!  @frankduncan, I fixed the way the errors show up on the different email inputs.  As @jasonaowen reported, we decided that changing the database was too tough and I [left a comment](https://github.com/SolutionGuidance/psm/issues/57#issuecomment-393918139) in #57.  Can you re-review?

**Comment by frankduncan** [comment]
Looks great!  thanks @cecilia-donnelly

**Pull request merged**
