### PR TITLE
Improve the Upload File UI on two pages

### LINKED ISSUE #734: Moving backward in PHN enrollment loses county contract
tl;dr: hitting "previous" traps you on a page and forgets the previously uploaded attachment

To reproduce,

1. start an enrollment application for a Public Health Nursing Organization
2. upload a county contract on the Facility Credentials page in the "PHN Agency must be a county or have a contract with a county" section
3. move forward in the application by filling out the rest of the page and clicking "Next"
4. click "Previous" to return to the Facility Credentials page
5. click "Next" to move on from this previously-completed page

Expected behavior:
The previously entered data is saved and accepted

Actual behavior:
The contract is lost, the error "Copy of contract with county is required for this provider type." is shown, and the field is highlighted as being in error.

contract-missing

Related to issue #158.

### PR DESCRIPTION
**Pull request by PaulMorris**
These commits are from @jasonaowen 's PR #1074. These two commits/pages did not work as expected so I'm separating them out into their own PR for further work.

On these pages (in the Public Health Nursing Organization and Physician Clinic applications), you can submit a file and the file name shows up as expected, but when you save as draft or move away from that page and go back, the button says "upload" again and there's no download link, as if you hadn't uploaded the file.  When logging in as an admin, the UI is the same ("upload" button), so it appears that the file is not being uploaded.

(I rebased the commits on master and did a tiny bit of reformatting.)

Issue #158 "No file selected" is confusing when a file is uploaded
Resolves #734 Moving backward in PHN enrollment loses county contract

### CODE REVIEW

**Comment by jasonaowen** [comment]
@PaulMorris it may be that we're not adding all the information needed to the model; I think I remember that problem on some of the other forms. It might be worthwhile to look at the variables we set in the form binder, and making sure we're including the previously-updated attachment ID in the variables we're searching.

Sorry to put partially completed work on your shoulders! Thanks for carrying this forward.

**Comment by PaulMorris** [comment]
Thanks for the tips @jasonaowen!  I took another look today, and the problem was just that I just did not check the checkbox (or radio button) next to the file upload button on these pages.  If you do that, then everything works as expected.  Navigating away from the page and coming back you still see the "Download/Replace" state, and after submitting the applications and logging in as an admin, you see the "Download/Replace" state when editing, and downloading the uploaded files succeeds.

So, nothing to see here...  In a follow-up it might be worth improving the UI to keep users from getting tripped up by this (e.g. disable upload button until checkbox is checked), but this PR is ready for review and merging.  I'll remove the WIP status.  Screenshots for the record:

Public Health Nursing Organization:

screenshot_2018-09-18 facility credentials 1

Physician Clinic:

screenshot_2018-09-18 facility credentials 2

**Comment by PaulMorris** [comment]
I checked and this PR does resolve issue #734.

**Comment by PaulMorris** [comment]
I'm going to merge this.  I've reviewed @jasonaowen 's work and I didn't add anything so there's nothing else to review.

**Pull request merged**
