### PR TITLE
Update developer installation instruction note in INSTALL.md

### PR DESCRIPTION
**Pull request by kellysouza**
In order to keep users apprised of the status of our production deployment guide, this updates the note in INSTALL.md informing users the production deployment guide will be a part of the initial release.

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
@kellysouza, seconding everything @PaulMorris said!  And one more thing: please remove the date from the note.  The October date is no longer correct, and there's no particular need to add a specific date to the new notice IMO.

**Comment by kellysouza** [comment]
Thank you for the feedback. The PR and comment are updated.

**Comment by cecilia-donnelly** [comment]
@kellysouza Thanks!  One more thing: we try to keep our commit history clean with liberal use of `git rebase` and `force push`.  Can you do that instead of merging master into your branch?

**Comment by kellysouza** [comment]
Fixed PR to include only relevant commit, will rebase in future to avoid muddying up the git history.

**Comment by kellysouza** [comment]
Thank you @cecilia-donnelly !

**Pull request merged**
