### PR TITLE
Move to ansible for demo setup

### PR DESCRIPTION
**Pull request by jvasile**
This patch takes all the steps in the install.sh and recasts them as an ansible role.  It replaces the original install.sh script with a couple lines that invoke ansible.

### CODE REVIEW

**Comment by jvasile** [comment]
Hmm... this is failing some manual testing.  I'll fix and update it.

**Comment by PaulMorris** [comment]
I added a commit that adds the liquibase db setup step.  I haven't had a chance to test this yet.

**Comment by frankduncan** [comment]
I noticed that the "Seed Database" still cats seed.sql, so that can be removed.

Otherwise, this all looks straightforward and correct to me.  I don't have an ubuntu or fedora machine handy, but we may want to create an issue to track the idea of making ansible the default way to install the app on jenkins in the future, otherwise this will only ever get tested when someone new onboards, and the likelihood of it going stale is probably pretty high.

**Comment by PaulMorris** [comment]
I've removed the "seed.sql" file from the "Seed Database" step.  Will go ahead and merge since this is more up-to-date than the script it is replacing.

**Comment by PaulMorris** [comment]
I've opened Issue #1099 "Use ansible script for installing on Jenkins" to track that idea, as @frankduncan suggested.

**Pull request merged**
