### PR TITLE
454 fix license renewal end date for pca

### PR DESCRIPTION
**Pull request by lorinpa**
On both the 'Register New' and the edit existing enrollment application pages, 'Personal Care Assistant Enrollment Application' > training tab. Enable an optional license/certification renewal end date.

This pull request also adds serenity tests verifying the 'optional license/certification renewal end date', works as expected.

Issue #454 License renewal end date grayed out for pca

### CODE REVIEW

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Comment by lorinpa** [comment]
Hi Jason @jasonaowen ,
Thank you for the review. Per your instructions I've:

- Resolved the style issues

- Squashed the commits into a 'stand alone' change set (I.E. combined the commits).

**Comment by jasonaowen** [comment]
Jenkins, test this please.

**Comment by lorinpa** [comment]
Hi Jason @jasonaowen , Thank you!!

**Pull request merged**
