### PR TITLE
Add npm

### PR DESCRIPTION
**Pull request by jasonaowen**
We want to be able to use npm to manage some of our JavaScript dependencies, such as for adding accessibility tools (issue #518, PR #639) or linting our JavaScript (issue #456, PR #428). 

This doesn't use npm yet, but it sets the stage by moving all of our current JavaScript out of `cms-web` and into a new project, `frontend`, and adds a [Gradle plugin that manages npm](https://github.com/srs/gradle-node-plugin).

Someday, we can add webpack or similar to allow us to split up our JavaScript files into components and then bundle them back together for the browser to download, and babel to allow us to write ES6 or later JavaScript that is compatible with older browsers. For now, though, this is a good, small step in that direction.

---

I tested this by building and deploying, and verifying that everything still continues to work by running the integration tests.

---

Issue #626 Manage JavaScript dependencies and modernize build

### CODE REVIEW

**Comment by jasonaowen** [comment]
After trying to add JSCS as a linter, it occurs to me that it might be worthwhile to separate our vendored scripts into a separate directory until they're all migrated to webjars or npm dependencies. Let me figure out how best to do that.

**Comment by jasonaowen** [comment]
Okay, updated to split our checked-in third-party JavaScript in `psm-app/frontend/src/vendor/js`.

**Comment by PaulMorris** [comment]
I looked through the code changes, built and deployed the app, ran the integration tests, and navigated around the site a bit.  Everything's working as expected.

**Comment by jasonaowen** [comment]
Here's some more information about [package-lock.json](https://docs.npmjs.com/files/package-lock.json). tl;dr: it's an automatically generated file based on the result of doing an `npm install` from `package.json`; it is intended to be committed.

> this creates new tasks, `frontend:npmSetup` and `frontend:npmInstall`. Will we need to run this?

We don't need to run them manually unless we're actively doing things with npm, such as installing new packages during development.

I have a branch that I'll open a PR for after this PR that demonstrates one way of using it, but the plugin manages dependencies automatically so that you don't need to manually or explicitly run those targets.

**Pull request merged**
