### PR TITLE
Use HTML5 instead of XHTML

### LINKED ISSUE #613: Use HTML5 instead of XHTML
Using HTML5 will allow us to use built-in placeholder text (c.f. #612) and other modern features.  We can add more advantages to this issue as we come across them -- there may be some changes related to the accessibility work, as well.

@jasonaowen points to this [reference article](http://oli.jp/2009/html5-structure4/).

### PR DESCRIPTION
**Pull request by jasonaowen**
Switch the DOCTYPE and <html> tags from XHTML to HTML5, so that we can start using HTML5 features.

I tested this by poking around in the app with the dev tools console open and watching for warnings or errors.

Resolves #613 Use HTML5 instead of XHTML

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
@PaulMorris, would you review this?  I don't know much about the difference between HTML5 and XHTML, and I'd like to have your more-experienced eyes on it.

**Comment by jasonaowen** [comment]
Oh, great find, @PaulMorris ! Thank you, I'll make those changes.

**Comment by jasonaowen** [comment]
@PaulMorris updated! Please let me know if I missed anything.

**Comment by PaulMorris** [comment]
@jasonaowen Looks good!  I didn't find anything you missed.  Thanks again -- it will be really nice to be able to take advantage of newer html5 features.

**Pull request merged**
